name: Solana Provider Package

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "packages/solana-provider/src/**"
    tags:
      - "solana-provider@*"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "packages/solana-provider/src/**"
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/solana-provider@')
    uses: ./.github/workflows/_publish-npm-package.yml
    permissions:
      contents: write
      id-token: write
    with:
      package-name: solana-provider
