name: Auth Client Package

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "packages/auth-client/src/**"
      - "packages/auth-client/scripts/**"
    tags:
      - "auth-client@*"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "packages/auth-client/src/**"
      - "packages/auth-client/scripts/**"
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/auth-client@')
    uses: ./.github/workflows/_publish-npm-package.yml
    permissions:
      contents: write
      id-token: write
    with:
      package-name: auth-client
