name: React Package

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "packages/react/src/**"
      - "packages/react/scripts/**"
    tags:
      - "react@*"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "packages/react/src/**"
      - "packages/react/scripts/**"
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/react@')
    uses: ./.github/workflows/reusable-publish-npm-package.yml
    permissions:
      contents: write
      id-token: write
    with:
      package-name: react
